name: Run ECS Task

on:
  push
jobs:
  listS3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
      # All commands after this point have access to the AWS CLI
      - run: aws ecs run-task --cluster newcls --task-definition nginxtaskdef --count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[subnet-0d5de275],securityGroups=[sg-08495eda3967b5855]}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
